//
//  mipc_def_manager.h
//  mipci
//
//  Created by mining on 14-7-24.
//
//

//字典
#define DEFLIST_N2O @{\
@"ccm_record_task_get":@"CcmGetRecordingTaskConfigurationRequest",\
@"ccm_play_ack":@"GetStreamUriResponse",\
@"ccm_ntp_get_ack":@"GetNTPResponse",\
@"ccm_upgrade_ack":@"CcmUpgradeResponse",\
@"ccm_dev_add_ack":@"CcmAddSubDeviceResponse",\
@"ccm_upgrade_get":@"CcmGetUpgradeStatusRequest",\
@"ccm_speakers_get_ack":@"GetAudioOutputsResponse",\
@"ccm_server_get_ack":@"CcmServerGetResponse",\
@"ccm_mic_set_ack":@"SetAudioSourceConfigurationResponse",\
@"ccm_info_get_ack":@"CcmGetDeviceResponse",\
@"ccm_restore_ack":@"RestoreSystemResponse",\
@"ccm_record_task_get_ack":@"CcmGetRecordingTaskConfigurationResponse",\
@"ccm_alert_dev_set_ack":@"CcmAlertDeviceSetResponse",\
@"ccm_alert_dev_set":@"CcmAlertDeviceSetRequest",\
@"ccm_img_get_ack":@"GetImagingSettingsResponse",\
@"ccm_sd_get":@"CcmGetSDCardStatusRequest",\
@"ccm_dev_del_ack":@"CcmDelSubDeviceResponse",\
@"ccm_img_set":@"SetImagingSettingsRequest",\
@"ccm_alert_action":@"CcmAlertAction",\
@"ccm_speaker_get":@"GetAudioOutputConfigurationRequest",\
@"ccm_osd_set":@"CcmSetOsdRequest",\
@"ccm_net_set_ack":@"CcmSetNetworkInfoResponse",\
@"ccm_ptz_ctl_ack":@"RelativeMoveResponse",\
@"ccm_video_srcs_get_ack":@"GetVideoSourcesResponse",\
@"ccm_ptz_ctl":@"RelativeMoveRequest",\
@"ccm_speaker_set":@"SetAudioOutputConfigurationRequest",\
@"ccm_info_get":@"CcmGetDeviceRequest",\
@"ccm_devs_get_ack":@"CcmGetSubDevicesResponse",\
@"ccm_restore":@"RestoreSystemRequest",\
@"ccm_record_task_set":@"CcmSetRecordingTaskConfigurationRequest",\
@"ccm_alert_action_get_ack":@"CcmAlertActionGetResponse",\
@"ccm_server_set":@"CcmServerSetRequest",\
@"ccm_ptz_nodes_get":@"GetNodesRequest",\
@"ccm_mics_get":@"GetAudioSourcesRequest",\
@"ccm_date_set":@"SetSystemDateAndTimeRequest",\
@"ccm_msg":@"ccm_message",\
@"ccm_ptz_nodes_get_ack":@"GetNodesResponse",\
@"ccm_speaker_get_ack":@"GetAudioOutputConfigurationResponse",\
@"ccm_profile_get":@"GetProfileRequest",\
@"ccm_msg_get_ack":@"ccm_message_search_ack",\
@"ccm_date_set_ack":@"SetSystemDateAndTimeResponse",\
@"ccm_snapshot_ack":@"GetSnapshotUriResponse",\
@"ccm_mic_get_ack":@"GetAudioSourceConfigurationsResponse",\
@"ccm_video_srcs_get":@"GetVideoSourcesRequest",\
@"ccm_upgrade_get_ack":@"CcmGetUpgradeStatusResponse",\
@"ccm_alert_action_set":@"CcmAlertActionSetRequest",\
@"ccm_dev_info_get":@"GetDeviceInformationRequest",\
@"ccm_disk_get":@"CcmGetDisksRequest",\
@"ccm_subscribe_ack":@"CcmSubscribeResponse",\
@"ccm_date_get":@"GetSystemDateAndTimeRequest",\
@"ccm_reboot_ack":@"SystemRebootResponse",\
@"ccm_sd_get_ack":@"CcmGetSDCardStatusResponse",\
@"ccm_mics_get_ack":@"GetAudioSourcesResponse",\
@"ccm_osd_get_ack":@"CcmGetOsdsResponse",\
@"ccm_lic_info":@"CcmLicenseInfo",\
@"ccm_server_set_ack":@"CcmServerSetResponse",\
@"ccm_alert_dev_get":@"CcmAlertDeviceGetRequest",\
@"ccm_talk":@"CcmGetAudioOutputStreamUriRequest",\
@"ccm_talk_ack":@"CcmGetAudioOutputStreamUriResponse",\
@"ccm_upgrade":@"CcmUpgradeRequest",\
@"ccm_date_get_ack":@"GetSystemDateAndTimeResponse",\
@"ccm_snapshot":@"GetSnapshotUriRequest",\
@"ccm_alert_action_set_ack":@"CcmAlertActionSetResponse",\
@"ccm_mic_set":@"SetAudioSourceConfigurationRequest",\
@"ccm_disk_ctl_ack":@"CcmDiskCtrlResponse",\
@"ccm_osd_set_ack":@"CcmSetOsdResponse",\
@"ccm_mic_get":@"GetAudioSourceConfigurationsRequest",\
@"ccm_play":@"GetStreamUriRequest",\
@"ccm_ntp_get":@"GetNTPRequest",\
@"ccm_profiles_get_ack":@"GetProfilesRequest",\
@"ccm_speakers_get":@"GetAudioOutputsRequest",\
@"ccm_disk_ctl":@"CcmDiskCtrlRequest",\
@"ccm_nick_set_ack":@"CcmSetDeviceNickResponse",\
@"ccm_server_get":@"CcmServerGetRequest",\
@"ccm_alert_action_del_ack":@"CcmAlertActionDelResponse",\
@"ccm_alert_dev_get_ack":@"CcmAlertDeviceGetResponse",\
@"ccm_disk_get_ack":@"CcmGetDisksResponse",\
@"ccm_proxy_invite":@"CcmProxyInviteRequest",\
@"ccm_misc_set":@"CcmSetSystemInfoRequest",\
@"ccm_img_set_ack":@"SetImagingSettingsResponse",\
@"ccm_misc_set_ack":@"CcmSetSystemInfoResponse",\
@"ccm_ntp_set_ack":@"SetNTPResponse",\
@"ccm_devs_get":@"CcmGetSubDevicesRequest",\
@"ccm_msg_get":@"ccm_message_search",\
@"ccm_reboot":@"SystemRebootRequest",\
@"ccm_net_set":@"CcmSetNetworkInfoRequest",\
@"ccm_dev_info_get_ack":@"GetDeviceInformationResponse",\
@"ccm_pwd_set":@"SetUserRequest",\
@"ccm_pwd_set_ack":@"SetUserResponse",\
@"ccm_img_get":@"GetImagingSettingsRequest",\
@"ccm_dev_add":@"CcmAddSubDeviceRequest",\
@"ccm_osd_get":@"CcmGetOsdsRequest",\
@"ccm_dev_del":@"CcmDelSubDeviceRequest",\
@"ccm_ntp_set":@"SetNTPRequest",\
@"ccm_nick_set":@"CcmSetDeviceNickRequest",\
@"ccm_misc_get_ack":@"CcmGetSystemInfoResponse",\
@"ccm_alert_action_get":@"CcmAlertActionGetRequest",\
@"ccm_profile_get_ack":@"GetProfileResponse",\
@"ccm_replay":@"GetReplayUriRequest",\
@"ccm_record_task_set_ack":@"CcmSetRecordingTaskConfigurationResponse",\
@"ccm_subscribe":@"CcmSubscribeRequest",\
@"ccm_net_get":@"CcmGetNetworkInfoRequest",\
@"ccm_pic_get":@"CcmGetImageRequest",\
@"ccm_net_get_ack":@"CcmGetNetworkInfoResponse",\
@"ccm_ack":@"CcmCommResponse",\
@"ccm_misc_get":@"CcmGetSystemInfoRequest",\
@"ccm_replay_ack":@"GetReplayUriResponse",\
}

#define DEFLIST_O2N @{@"CcmGetDeviceRequest":@"ccm_info_get",\
@"CcmGetSubDevicesRequest":@"ccm_devs_get",\
@"CcmGetDeviceResponse":@"ccm_info_get_ack",\
@"CcmGetSubDevicesResponse":@"ccm_devs_get_ack",\
@"CcmAddSubDeviceRequest":@"ccm_dev_add",\
@"CcmAddSubDeviceResponse":@"ccm_dev_add_ack",\
@"CcmDelSubDeviceRequest":@"ccm_dev_del",\
@"CcmDelSubDeviceResponse":@"ccm_dev_del_ack",\
@"CcmSetDeviceNickRequest":@"ccm_nick_set",\
@"CcmSetDeviceNickResponse":@"ccm_nick_set_ack",\
@"GetDeviceInformationRequest":@"ccm_dev_info_get",\
@"GetDeviceInformationResponse":@"ccm_dev_info_get_ack",\
@"SetUserRequest":@"ccm_pwd_set",\
@"SetUserResponse":@"ccm_pwd_set_ack",\
@"SetSystemDateAndTimeRequest":@"ccm_date_set",\
@"SetSystemDateAndTimeResponse":@"ccm_date_set_ack",\
@"GetSystemDateAndTimeRequest":@"ccm_date_get",\
@"GetSystemDateAndTimeResponse":@"ccm_date_get_ack",\
@"GetNTPRequest":@"ccm_ntp_get",\
@"GetNTPResponse":@"ccm_ntp_get_ack",\
@"SetNTPRequest":@"ccm_ntp_set",\
@"SetNTPResponse":@"ccm_ntp_set_ack",\
@"CcmUpgradeRequest":@"ccm_upgrade",\
@"CcmUpgradeResponse":@"ccm_upgrade_ack",\
@"CcmGetUpgradeStatusRequest":@"ccm_upgrade_get",\
@"CcmGetUpgradeStatusResponse":@"ccm_upgrade_get_ack",\
@"SystemRebootRequest":@"ccm_reboot",\
@"SystemRebootResponse":@"ccm_reboot_ack",\
@"RestoreSystemRequest":@"ccm_restore",\
@"RestoreSystemResponse":@"ccm_restore_ack",\
@"GetVideoSourcesResponse":@"ccm_video_srcs_get_ack",\
@"GetVideoSourcesRequest":@"ccm_video_srcs_get",\
@"GetAudioSourcesRequest":@"ccm_mics_get",\
@"GetAudioSourcesResponse":@"ccm_mics_get_ack",\
@"GetAudioSourceConfigurationsRequest":@"ccm_mic_get",\
@"GetAudioSourceConfigurationsResponse":@"ccm_mic_get_ack",\
@"GetProfileRequest":@"ccm_profile_get",\
@"GetProfileResponse":@"ccm_profile_get_ack",\
@"GetProfilesRequest":@"ccm_profiles_get_ack",\
@"SetAudioSourceConfigurationRequest":@"ccm_mic_set",\
@"SetAudioSourceConfigurationResponse":@"ccm_mic_set_ack",\
@"GetStreamUriRequest":@"ccm_play",\
@"GetStreamUriResponse":@"ccm_play_ack",\
@"GetSnapshotUriRequest":@"ccm_snapshot",\
@"GetSnapshotUriResponse":@"ccm_snapshot_ack",\
@"CcmGetRecordingTaskConfigurationRequest":@"ccm_record_task_get",\
@"CcmGetRecordingTaskConfigurationResponse":@"ccm_record_task_get_ack",\
@"CcmSetRecordingTaskConfigurationRequest":@"ccm_record_task_set",\
@"CcmSetRecordingTaskConfigurationResponse":@"ccm_record_task_set_ack",\
@"GetReplayUriRequest":@"ccm_replay",\
@"GetAudioOutputsRequest":@"ccm_speakers_get",\
@"GetAudioOutputsResponse":@"ccm_speakers_get_ack",\
@"GetAudioOutputConfigurationRequest":@"ccm_speaker_get",\
@"GetAudioOutputConfigurationResponse":@"ccm_speaker_get_ack",\
@"SetAudioOutputConfigurationRequest":@"ccm_speaker_set",\
@"CcmGetDisksRequest":@"ccm_disk_get",\
@"CcmGetDisksResponse":@"ccm_disk_get_ack",\
@"CcmDiskCtrlRequest":@"ccm_disk_ctl",\
@"CcmDiskCtrlResponse":@"ccm_disk_ctl_ack",\
@"ccm_message":@"ccm_msg",\
@"ccm_message_search":@"ccm_msg_get",\
@"ccm_message_search_ack":@"ccm_msg_get_ack",\
@"GetNodesRequest":@"ccm_ptz_nodes_get",\
@"GetNodesResponse":@"ccm_ptz_nodes_get_ack",\
@"RelativeMoveRequest":@"ccm_ptz_ctl",\
@"RelativeMoveResponse":@"ccm_ptz_ctl_ack",\
@"GetImagingSettingsRequest":@"ccm_img_get",\
@"GetImagingSettingsResponse":@"ccm_img_get_ack",\
@"SetImagingSettingsRequest":@"ccm_img_set",\
@"SetImagingSettingsResponse":@"ccm_img_set_ack",\
@"CcmGetOsdsRequest":@"ccm_osd_get",\
@"CcmGetOsdsResponse":@"ccm_osd_get_ack",\
@"CcmSetOsdRequest":@"ccm_osd_set",\
@"CcmLicenseInfo":@"ccm_lic_info",\
@"CcmServerSetRequest":@"ccm_server_set",\
@"CcmServerSetResponse":@"ccm_server_set_ack",\
@"CcmServerGetRequest":@"ccm_server_get",\
@"CcmServerGetResponse":@"ccm_server_get_ack",\
@"CcmProxyInviteRequest":@"ccm_proxy_invite",\
@"CcmGetSDCardStatusRequest":@"ccm_sd_get",\
@"CcmGetSDCardStatusResponse":@"ccm_sd_get_ack",\
@"CcmGetAudioOutputStreamUriRequest":@"ccm_talk",\
@"CcmGetAudioOutputStreamUriResponse":@"ccm_talk_ack",\
@"CcmSetNetworkInfoRequest":@"ccm_net_set",\
@"CcmSetNetworkInfoResponse":@"ccm_net_set_ack",\
@"CcmSetSystemInfoRequest":@"ccm_misc_set",\
@"CcmSetSystemInfoResponse":@"ccm_misc_set_ack",\
@"CcmGetSystemInfoResponse":@"ccm_misc_get_ack",\
@"CcmSubscribeRequest":@"ccm_subscribe",\
@"CcmSubscribeResponse":@"ccm_subscribe_ack",\
@"CcmAlertDeviceSetRequest":@"ccm_alert_dev_set",\
@"CcmAlertDeviceSetResponse":@"ccm_alert_dev_set_ack",\
@"CcmAlertDeviceGetRequest":@"ccm_alert_dev_get",\
@"CcmAlertDeviceGetResponse":@"ccm_alert_dev_get_ack",\
@"CcmAlertAction":@"ccm_alert_action",\
@"CcmAlertActionGetRequest":@"ccm_alert_action_get",\
@"CcmAlertActionGetResponse":@"ccm_alert_action_get_ack",\
@"CcmAlertActionSetRequest":@"ccm_alert_action_set",\
@"CcmAlertActionSetResponse":@"ccm_alert_action_set_ack",\
@"CcmAlertActionDelResponse":@"ccm_alert_action_del_ack",\
@"CcmGetNetworkInfoRequest":@"ccm_net_get",\
@"CcmGetNetworkInfoResponse":@"ccm_net_get_ack",\
@"CcmGetImageRequest":@"ccm_pic_get",\
@"CcmCommResponse":@"ccm_ack",\
@"CcmGetSystemInfoRequest":@"ccm_misc_get",\
@"GetReplayUriResponse":@"ccm_replay_ack",\
@"CcmSetOsdResponse":@"ccm_osd_set_ack",\
}


#import <Foundation/Foundation.h>
#import "mipc_data_object.h"

@interface mipc_def_manager : NSObject

@property(nonatomic,strong) NSMutableDictionary   *def_obj_list;

@property (assign, nonatomic) struct pack_def_list *new_def_list;
@property (assign, nonatomic) struct pack_def_list *old_def_list;

+ (mipc_def_manager*)shared_def_manager;
- (void)checkMsgRsp:(mjson_msg*)msg;
- (void)checkMsgRqt:(NSString**)type dataJson:(NSString**)dataJson;

@end
